# Perfil de desenvolvimento
spring.profiles.active=dev

# Mail: simulação ligada em dev
app.mail.simulate=true
spring.mail.debug=true

# Host/porta (pode usar Mailtrap aqui se preferir)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:465}

# Credenciais deixadas em branco (use variáveis de ambiente se quiser testar envio real)
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

# SSL por padrão (pode alternar para 587/STARTTLS se necessário)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}
